### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [martseniuk-bogdan/martseniuk-bogdan#5]
1. Добавить модификаторы доступа конструкторам и всем остальным методам.
2. Зачем count++ в getModel?
3. phNumber - можно просто number. И так понятно, что phone number.
4. Добавьте finalize

**Comment by martseniuk-bogdan** [comment]
исправил и запушил

**Comment by milkina** [comment]
1. Исправить имена для геттеров и сеттеров
2. В finalize сделать count++.

**Comment by martseniuk-bogdan** [comment]
В finalize сделать count++. - имеется ввиду вывести сам счетчик?
